---
title: "Homework 1"
author: "Jie Chen"
date: '2018-09-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1 (Chapter 2, #1, 8 marks)

(a) <Flexible is better because it 
can use the abundance of data points (large n) to give a good fit.>

(b) <Flexible is worse because it
takes more data (n) to fit.>

(c) <Flexible is better because it 
will have the flexibility to fit the non-linear relationship.>

(d) <Flexible is worse because it
will try to fit the error.>

## Question 2 (Chapter 2, #2, 6 marks)

(a) <This is a regression problem and we 
are most interested in inference. 
n=500, p=3.>

(b) <This is a classification problem and we
are  most interested in prediction.
n=20, p=4.>

(c) <This is a regression problem and we are
most interested in prediction.
n=52, p=3.>

## Question 3 (Chapter 2, #9, 8 marks)

```{r}
library(ISLR) # use install.packages("ISLR") to install
data(Auto)
head(Auto)
```

(a) <Origin and name are qualitative and the other seven
are quantitative.> 

(b) <

```{r}
# Hints:
#   with(Auto,range(mpg)); with(Auto,range(cylinders)), etc.
# or you can use apply() on subsets of columns
apply(Auto[,1:5],MARGIN=2,FUN=range)
# or we can name the output of range and call apply
myr <- function(x) {
  out <- range(x)
  names(out) <- c("min","max")
  out
}
apply(Auto[,1:5],MARGIN=2,FUN=myr)
```


(c)

```{r}
# Hint
meansd <- function(x) {
  out<-c(mean(x),sd(x))
  names(out) <- c("mean","SD")
  out
}
```


(d)

```{r}
# Hint:
AutoSubset <- Auto[c(1:9,86:nrow(Auto)),1:7]
```

(e)The variables 'cylinders', 'displacement', 'housepower'
and 'weight' are positively correlated with each other
and negatively correlated with "mpg'.

(f) Mpg associated with all of the quantitative variables.
