---
title: "Week 2 Exercises"
author: "Brad McNeney"
date: '2017-09-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gapminder data

1. If you have not already done so,
install the `gapminder`, `ggplot2` and `dplyr` packages 
from CRAN using either
the `Tools -> Install Packages` 
menu or the `install.packages()` function from 
the command line.

2. Use the `library()` command to load these three
packages, and use
`data()` to load the `gapminder` dataset.


3. Use `help("gapminder")` to learn about the
dataset, `head()` to examine the variable names and 
`summary()` to get a summary of each variable. What
does the summary of the `gdpPercap` variable tell you
about its distribution?

4. Add the natural log of `gdpPercap` to the dataset using
the `mutate()` function from `dplyr`. Call your new
variable `lgdpPercap`.

5. Use `filter()` to 
create a new dataset `gm1952` that contains the 
data in `gapminder` that is 
- from the year 1952, and
- from either Africa, Europe or Asia.

6. Similarly create `gm2007` comprised of the `gapminder` 
data from 2007 on Africa, Europe and Asia. 

7. Use `ggplot()` to  plot `lifeExp` _vs_ `lgdpPercap`
from the `gm1952` dataset.
Use the aesthetic `color=continent` to get different
colours for contries from the different continents.
Add least squares lines for each continent. Suppress
the confidence bands on the least squares lines.
Do you see any outliers with respect to `lgdpPercap`?
If you do see any outliers,
search for the countries using either
`filter()` to subset the data,
`View()` to view the data.


8. Repeat the plot from (6) with the 2007 data. Do you
see any outliers with respect to `lifeExp`? 
If you do see any outliers,
search for the countries using either
`filter()` to subset the data,
`View()` to view the data.


9. Comment on differences between the 1952 and 2007 
plots.
